/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import asymmetric.Elgamal;
import symmetric.MagicSquaer;
import symmetric.PolyalphabeticCipher;

/**
 *
 * @author egor
 */
public class MainFrame extends javax.swing.JFrame {
    private String inputText;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        symmetricGroup = new javax.swing.ButtonGroup();
        asymmetricGroup = new javax.swing.ButtonGroup();
        inputLine = new javax.swing.JTextField();
        encodeLine = new javax.swing.JTextField();
        decodeLine = new javax.swing.JTextField();
        encodeButton = new javax.swing.JButton();
        decodeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        algorithmTabbedPane = new javax.swing.JTabbedPane();
        symmetricPanel = new javax.swing.JPanel();
        SymA_magic = new javax.swing.JRadioButton();
        SymA_poly = new javax.swing.JRadioButton();
        asymmetricPanel = new javax.swing.JPanel();
        rsaRadioButton = new javax.swing.JRadioButton();
        elgamalRadioButton = new javax.swing.JRadioButton();
        generateKeysButton = new javax.swing.JButton();
        publicKeyPanel = new javax.swing.JPanel();
        yField = new javax.swing.JTextField();
        pField = new javax.swing.JTextField();
        gField = new javax.swing.JTextField();
        pLabel = new javax.swing.JLabel();
        gLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        privateKeyPanel = new javax.swing.JPanel();
        xField = new javax.swing.JTextField();
        xLabel = new javax.swing.JLabel();
        PGPPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coder");

        encodeButton.setText("encode");
        encodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeButtonActionPerformed(evt);
            }
        });

        decodeButton.setText("decode");
        decodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeButtonActionPerformed(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Input");

        jLabel2.setText("encode");

        jLabel3.setText("decode");

        symmetricGroup.add(SymA_magic);
        SymA_magic.setSelected(true);
        SymA_magic.setText("magic Square");
        SymA_magic.setToolTipText("");

        symmetricGroup.add(SymA_poly);
        SymA_poly.setText("polyalphabetic cipher");

        javax.swing.GroupLayout symmetricPanelLayout = new javax.swing.GroupLayout(symmetricPanel);
        symmetricPanel.setLayout(symmetricPanelLayout);
        symmetricPanelLayout.setHorizontalGroup(
            symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SymA_magic)
                    .addComponent(SymA_poly))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        symmetricPanelLayout.setVerticalGroup(
            symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SymA_magic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SymA_poly)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        algorithmTabbedPane.addTab("Symmetric", symmetricPanel);

        asymmetricGroup.add(rsaRadioButton);
        rsaRadioButton.setText("rsa");

        asymmetricGroup.add(elgamalRadioButton);
        elgamalRadioButton.setSelected(true);
        elgamalRadioButton.setText("Elgamal");
        elgamalRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                elgamalRadioButtonStateChanged(evt);
            }
        });

        generateKeysButton.setText("Generate");
        generateKeysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateKeysButtonActionPerformed(evt);
            }
        });

        publicKeyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Public key"));

        yField.setEnabled(false);

        pField.setEnabled(false);

        gField.setEnabled(false);

        pLabel.setText("p :");

        gLabel.setText("g :");

        yLabel.setText("y :");

        javax.swing.GroupLayout publicKeyPanelLayout = new javax.swing.GroupLayout(publicKeyPanel);
        publicKeyPanel.setLayout(publicKeyPanelLayout);
        publicKeyPanelLayout.setHorizontalGroup(
            publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicKeyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(yField)
                    .addComponent(pField)
                    .addComponent(gField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap())
        );
        publicKeyPanelLayout.setVerticalGroup(
            publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicKeyPanelLayout.createSequentialGroup()
                .addGroup(publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(publicKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yLabel)))
        );

        privateKeyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Private key"));

        xField.setEnabled(false);

        xLabel.setText("x :");

        javax.swing.GroupLayout privateKeyPanelLayout = new javax.swing.GroupLayout(privateKeyPanel);
        privateKeyPanel.setLayout(privateKeyPanelLayout);
        privateKeyPanelLayout.setHorizontalGroup(
            privateKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, privateKeyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        privateKeyPanelLayout.setVerticalGroup(
            privateKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(privateKeyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(xLabel))
        );

        javax.swing.GroupLayout asymmetricPanelLayout = new javax.swing.GroupLayout(asymmetricPanel);
        asymmetricPanel.setLayout(asymmetricPanelLayout);
        asymmetricPanelLayout.setHorizontalGroup(
            asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asymmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsaRadioButton)
                    .addComponent(generateKeysButton)
                    .addComponent(elgamalRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(privateKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(publicKeyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        asymmetricPanelLayout.setVerticalGroup(
            asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(asymmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(asymmetricPanelLayout.createSequentialGroup()
                        .addComponent(elgamalRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generateKeysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(asymmetricPanelLayout.createSequentialGroup()
                        .addComponent(publicKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(privateKeyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rsaRadioButton))
                .addContainerGap())
        );

        algorithmTabbedPane.addTab("Asymmetric", asymmetricPanel);

        javax.swing.GroupLayout PGPPanelLayout = new javax.swing.GroupLayout(PGPPanel);
        PGPPanel.setLayout(PGPPanelLayout);
        PGPPanelLayout.setHorizontalGroup(
            PGPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        PGPPanelLayout.setVerticalGroup(
            PGPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        algorithmTabbedPane.addTab("PGP", PGPPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decodeLine)
                    .addComponent(inputLine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(encodeLine)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(decodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(algorithmTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(algorithmTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encodeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decodeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodeButton)
                    .addComponent(clearButton)
                    .addComponent(decodeButton))
                .addContainerGap())
        );

        algorithmTabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // clear all lines
        inputLine.setText(null);
        encodeLine.setText(null);
        decodeLine.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void encodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encodeButtonActionPerformed
        String inputText = inputLine.getText();
        String encode = "";
        
        if (algorithmTabbedPane.getSelectedComponent() == symmetricPanel) {
            if (SymA_magic.isSelected()) {
                encode = MagicSquaer.getInstace().encode(inputText);
            } else {
                encode = new PolyalphabeticCipher().encode(inputText);
            }
        }
        
        if (algorithmTabbedPane.getSelectedComponent() == asymmetricPanel) {
            if (rsaRadioButton.isSelected()) {
                
            } else {
                int p = Integer.parseInt(pField.getText());
                int g = Integer.parseInt(gField.getText());
                int y = Integer.parseInt(yField.getText());
                int x = Integer.parseInt(xField.getText());
                Elgamal.getInstace().setPublicKey(p, g, y);
                Elgamal.getInstace().setPrivateKey(x);
                encode = Elgamal.getInstace().encode(inputText);
            }
        }
        
        encodeLine.setText(encode);
    }//GEN-LAST:event_encodeButtonActionPerformed

    private void decodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decodeButtonActionPerformed
        String encode = encodeLine.getText();
        String decode = "";
        
        if (algorithmTabbedPane.getSelectedComponent() == symmetricPanel) {
            if (SymA_magic.isSelected()) {
                decode = MagicSquaer.getInstace().decode(encode);
            } else {
                decode = new PolyalphabeticCipher().decode(encode);
            }
        }
        
        if (algorithmTabbedPane.getSelectedComponent() == asymmetricPanel) {
            if (rsaRadioButton.isSelected()) {
                
            } else {
                decode = Elgamal.getInstace().decode(encode);
            }
        }
        
        decodeLine.setText(decode);
    }//GEN-LAST:event_decodeButtonActionPerformed

    private void elgamalRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_elgamalRadioButtonStateChanged
        boolean isVisible = elgamalRadioButton.isSelected();
        
        generateKeysButton.setVisible(isVisible);
        publicKeyPanel.setVisible(isVisible);
        privateKeyPanel.setVisible(isVisible);
    }//GEN-LAST:event_elgamalRadioButtonStateChanged

    private void generateKeysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateKeysButtonActionPerformed
        int p = 1279;
        int g = (int)((p - 2) * Math.random()) + 1;
        int x = (int)((p - 2) * Math.random()) + 1;
        int y = (int)(Math.pow(g, x)) % p;
        
        pField.setText(String.valueOf(p));
        gField.setText(String.valueOf(g));
        yField.setText(String.valueOf(y));
        xField.setText(String.valueOf(x));
    }//GEN-LAST:event_generateKeysButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PGPPanel;
    private javax.swing.JRadioButton SymA_magic;
    private javax.swing.JRadioButton SymA_poly;
    private javax.swing.JTabbedPane algorithmTabbedPane;
    private javax.swing.ButtonGroup asymmetricGroup;
    private javax.swing.JPanel asymmetricPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decodeButton;
    private javax.swing.JTextField decodeLine;
    private javax.swing.JRadioButton elgamalRadioButton;
    private javax.swing.JButton encodeButton;
    private javax.swing.JTextField encodeLine;
    private javax.swing.JTextField gField;
    private javax.swing.JLabel gLabel;
    private javax.swing.JButton generateKeysButton;
    private javax.swing.JTextField inputLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pField;
    private javax.swing.JLabel pLabel;
    private javax.swing.JPanel privateKeyPanel;
    private javax.swing.JPanel publicKeyPanel;
    private javax.swing.JRadioButton rsaRadioButton;
    private javax.swing.ButtonGroup symmetricGroup;
    private javax.swing.JPanel symmetricPanel;
    private javax.swing.JTextField xField;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField yField;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
}
