/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import symmetric.PolyalphabeticCipher;

/**
 *
 * @author egor
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputLine = new javax.swing.JTextField();
        encodeLine = new javax.swing.JTextField();
        decodeLine = new javax.swing.JTextField();
        encodeButton = new javax.swing.JButton();
        decodeButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        algorithmTabbedPane = new javax.swing.JTabbedPane();
        symmetricPanel = new javax.swing.JPanel();
        SymA_magic = new javax.swing.JRadioButton();
        SymA_poly = new javax.swing.JRadioButton();
        asymmetricPanel = new javax.swing.JPanel();
        PGPPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        encodeButton.setText("encode");
        encodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encodeButtonActionPerformed(evt);
            }
        });

        decodeButton.setText("decode");
        decodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decodeButtonActionPerformed(evt);
            }
        });

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Input");

        jLabel2.setText("encode");

        jLabel3.setText("decode");

        SymA_magic.setText("magic Square");
        SymA_magic.setToolTipText("");

        SymA_poly.setText("polyalphabetic cipher");

        javax.swing.GroupLayout symmetricPanelLayout = new javax.swing.GroupLayout(symmetricPanel);
        symmetricPanel.setLayout(symmetricPanelLayout);
        symmetricPanelLayout.setHorizontalGroup(
            symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SymA_magic)
                    .addComponent(SymA_poly))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        symmetricPanelLayout.setVerticalGroup(
            symmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symmetricPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SymA_magic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(SymA_poly)
                .addContainerGap())
        );

        algorithmTabbedPane.addTab("Symmetric", symmetricPanel);

        javax.swing.GroupLayout asymmetricPanelLayout = new javax.swing.GroupLayout(asymmetricPanel);
        asymmetricPanel.setLayout(asymmetricPanelLayout);
        asymmetricPanelLayout.setHorizontalGroup(
            asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        asymmetricPanelLayout.setVerticalGroup(
            asymmetricPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        algorithmTabbedPane.addTab("Asymmetric", asymmetricPanel);

        javax.swing.GroupLayout PGPPanelLayout = new javax.swing.GroupLayout(PGPPanel);
        PGPPanel.setLayout(PGPPanelLayout);
        PGPPanelLayout.setHorizontalGroup(
            PGPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        PGPPanelLayout.setVerticalGroup(
            PGPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        algorithmTabbedPane.addTab("PGP", PGPPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decodeLine)
                    .addComponent(inputLine, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(encodeLine)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(decodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(algorithmTabbedPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(algorithmTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encodeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decodeLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodeButton)
                    .addComponent(clearButton)
                    .addComponent(decodeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        algorithmTabbedPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // clear all lines
        inputLine.setText(null);
        encodeLine.setText(null);
        decodeLine.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void encodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encodeButtonActionPerformed
        String inputText = inputLine.getText();
        String encode = "";
        
        if (algorithmTabbedPane.getSelectedComponent() == symmetricPanel) {
            if (SymA_magic.isSelected()) {
                //encode = MagicSquaer().encode(inputText);
            } else {
                encode = new PolyalphabeticCipher().encode(inputText);
            }
        }
        
        encodeLine.setText(encode);
    }//GEN-LAST:event_encodeButtonActionPerformed

    private void decodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decodeButtonActionPerformed
        String encode = encodeLine.getText();
        String decode = "";
        
        if (algorithmTabbedPane.getSelectedComponent() == symmetricPanel) {
            if (SymA_magic.isSelected()) {
                //encode = MagicSquaer().decode(inputText);
            } else {
                decode = new PolyalphabeticCipher().decode(encode);
            }
        }
        
        decodeLine.setText(decode);
    }//GEN-LAST:event_decodeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PGPPanel;
    private javax.swing.JRadioButton SymA_magic;
    private javax.swing.JRadioButton SymA_poly;
    private javax.swing.JTabbedPane algorithmTabbedPane;
    private javax.swing.JPanel asymmetricPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton decodeButton;
    private javax.swing.JTextField decodeLine;
    private javax.swing.JButton encodeButton;
    private javax.swing.JTextField encodeLine;
    private javax.swing.JTextField inputLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel symmetricPanel;
    // End of variables declaration//GEN-END:variables
}
